-- PESQUISAR EPISODIO
CREATE OR REPLACE PROCEDURE USP_PESQUISAR_EPISODIO(
    E_NUMERO INT,
    E_TEMPORADA INT,
    E_CODIGO_SERIE CHAR
)
AS 
CURSOR PESQ IS 
    SELECT DURACAO, DATA_EXIBICAO, DESCECICAO 
      FROM EPISODIO
    WHERE NUMERO = E_NUMERO AND TEMPORADA = E_TEMPORADA AND CODIGO = E_CODIGO;
BEGIN
      OPEN PESQ;
      FETCH PESQ INTO RES;
      WHILE PESQ%FOUND LOOP
        -- RETORNO
        FETCH PESQ INTO RES;
      END LOOP;
      CLOSE PESQ;
END;

-- PESQUISAR SERIES
CREATE OR REPLACE PROCEDURE USP_PESQUISAR_SERIE(
  E_CODIGO_SERIE IN CHAR
)
AS CURSOR PESQ IS
  SELECT
    NOME_SERIE, DESCRICAO_SERIE
  FROM
    SERIE
  WHERE
    CODIGO_SERIE = E_CODIGO_SERIE;
    
  RES VARCHAR(40);
BEGIN
  OPEN PESQ;
  FETCH PESQ INTO RES;
  WHILE PESQ%FOUND LOOP
    -- RETORNO
    FETCH PESQ INTO RES;
  END LOOP;
  CLOSE PESQ;
END;